Tests: clear_top_level_tasks_on_exit: Fix assertion failures with a safer implementation
Specifically, the following kind of assertion no longer shows up when running
tests that use the clear_top_level_tasks_on_exit() context:

    AssertionError: WeakTaskRef refers to a task that is not in the task tree: r=Resource(...), task_ref=<_WeakTaskRef to <...> at 0x1154e6830>